// Shared blog derivation. Pure and data-only: it turns the generated
// public/data/blog-content.json document into the records the router, sitemap,
// llms.txt, RSS feed and both site audits all read, and it owns the
// indexability gates for the /blog route family.
//
// Same contract as _cities.js / _venues.js / _artist-cities.js: one derivation,
// no HTML, no I/O, no secrets, so a page can never disagree with the sitemap
// about whether it should be indexed.
//
// Source of truth for the content itself is content/blog/*.md; the JSON this
// module reads is generated by scripts/build-blog-content.mjs and kept in step
// by `npm run blog:check` (wired into test:mvp and prelaunch validation).

export const BLOG_INDEX_PATH = "/blog";
export const BLOG_TAG_PREFIX = "/blog/tags/";

// A post shorter than this is thin for the query it would compete on, so it
// renders 200 with a self-referencing canonical but stays out of the index and
// the sitemap — the same "render it, don't index it" treatment single-date
// artist-city pages get (docs/ROUTE_INDEXABILITY_POLICY.md).
export const MIN_INDEXABLE_POST_WORDS = 300;

// A tag page listing one post is that post with extra steps. Two is the point
// at which the grouping says something the post page does not.
export const MIN_INDEXABLE_TAG_POSTS = 2;

const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

function text(value) {
  return String(value ?? "").trim();
}

function slugList(value) {
  return (Array.isArray(value) ? value : []).map(text).filter((entry) => SLUG_PATTERN.test(entry));
}

/**
 * Normalize one raw record from blog-content.json. Anything malformed is
 * dropped rather than half-rendered: a post with no slug, title, description or
 * body cannot produce a useful page.
 *
 * @param {unknown} raw
 * @returns {object|null}
 */
function normalizePost(raw) {
  if (!raw || typeof raw !== "object") return null;
  const slug = text(raw.slug);
  const title = text(raw.title);
  const description = text(raw.description);
  const datePublished = text(raw.datePublished);
  const sections = Array.isArray(raw.sections) ? raw.sections.filter((section) => section && typeof section === "object") : [];
  if (!SLUG_PATTERN.test(slug) || !title || !description || !ISO_DATE.test(datePublished) || !sections.length) return null;

  const dateModified = ISO_DATE.test(text(raw.dateModified)) ? text(raw.dateModified) : datePublished;
  const wordCount = Number.isFinite(raw.wordCount) ? Number(raw.wordCount) : 0;

  return {
    slug,
    path: `/blog/${slug}`,
    title,
    seoTitle: text(raw.seoTitle) || `${title} | TourTicketCompare`,
    description,
    summary: text(raw.summary) || description,
    datePublished,
    dateModified,
    status: text(raw.status) || "published",
    author: text(raw.author) || "TourTicketCompare editorial team",
    tags: slugList(raw.tags),
    relatedGuides: slugList(raw.relatedGuides),
    relatedArtists: slugList(raw.relatedArtists),
    sources: (Array.isArray(raw.sources) ? raw.sources : [])
      .map((source) => ({ label: text(source?.label), url: text(source?.url) }))
      .filter((source) => source.label && source.url.startsWith("https://")),
    sections,
    wordCount
  };
}

/**
 * Every published post, newest first. Drafts are excluded here, which is what
 * makes `status: draft` a real gate — a draft has no route at all.
 *
 * @param {unknown} blogContent Parsed public/data/blog-content.json.
 * @returns {Array<object>}
 */
export function derivePosts(blogContent) {
  const raw = Array.isArray(blogContent?.posts) ? blogContent.posts : [];
  return raw
    .map(normalizePost)
    .filter((post) => post && post.status === "published")
    .sort((a, b) => (a.datePublished === b.datePublished ? a.slug.localeCompare(b.slug) : b.datePublished.localeCompare(a.datePublished)));
}

/**
 * Whether a published post is substantial enough to be indexed.
 *
 * @param {object} post
 * @returns {boolean}
 */
export function postIndexable(post) {
  return Boolean(post) && post.wordCount >= MIN_INDEXABLE_POST_WORDS;
}

export function findPost(posts, slug) {
  const wanted = text(slug);
  return (posts || []).find((post) => post.slug === wanted) || null;
}

/**
 * Tag records derived from the published posts, most-used first. `indexable`
 * follows MIN_INDEXABLE_TAG_POSTS counted over *indexable* posts, so a tag
 * cannot be indexed on the strength of posts that are themselves noindex.
 *
 * @param {Array<object>} posts
 * @returns {Array<object>}
 */
export function deriveTags(posts) {
  const byTag = new Map();
  for (const post of posts || []) {
    for (const tag of post.tags) {
      if (!byTag.has(tag)) byTag.set(tag, []);
      byTag.get(tag).push(post);
    }
  }
  return [...byTag.entries()]
    .map(([slug, tagPosts]) => {
      const indexablePosts = tagPosts.filter(postIndexable);
      return {
        slug,
        path: `${BLOG_TAG_PREFIX}${slug}`,
        label: tagLabel(slug),
        posts: tagPosts,
        postCount: tagPosts.length,
        indexable: indexablePosts.length >= MIN_INDEXABLE_TAG_POSTS,
        lastmod: tagPosts.map((post) => post.dateModified).sort().at(-1) || ""
      };
    })
    .sort((a, b) => (b.postCount === a.postCount ? a.slug.localeCompare(b.slug) : b.postCount - a.postCount));
}

export function findTag(tags, slug) {
  const wanted = text(slug);
  return (tags || []).find((tag) => tag.slug === wanted) || null;
}

// Connecting words that stay lowercase inside a tag label. Length is the wrong
// test — it lowercases "we" and "how" as readily as "and" — so the list is
// explicit and the first word is always capitalised regardless.
const TAG_LABEL_STOPWORDS = new Set(["a", "an", "and", "at", "for", "in", "of", "on", "or", "the", "to", "vs", "with"]);

/**
 * Human label for a tag slug ("ticket-fees" → "Ticket Fees").
 *
 * @param {string} slug
 * @returns {string}
 */
export function tagLabel(slug) {
  return text(slug)
    .split("-")
    .filter(Boolean)
    .map((word, index) => (index > 0 && TAG_LABEL_STOPWORDS.has(word) ? word : word[0].toUpperCase() + word.slice(1)))
    .join(" ");
}

/**
 * The blog index is indexable once it has something worth landing on. With no
 * indexable post it still renders (so the route never 404s and existing links
 * survive) but stays out of the index, matching how empty artist boards behave.
 *
 * @param {Array<object>} posts
 * @returns {boolean}
 */
export function blogIndexIndexable(posts) {
  return (posts || []).some(postIndexable);
}

export function blogLastmod(posts) {
  return (posts || []).map((post) => post.dateModified).filter((value) => ISO_DATE.test(value)).sort().at(-1) || "";
}

/**
 * Up to `limit` related posts for a post page: same-tag posts first (most
 * shared tags, then newest), then the newest remaining posts so a post with no
 * tag overlap is never a dead end.
 *
 * @param {Array<object>} posts All published posts.
 * @param {object} post
 * @param {number} [limit]
 * @returns {Array<object>}
 */
export function relatedPosts(posts, post, limit = 3) {
  const others = (posts || []).filter((candidate) => candidate.slug !== post?.slug);
  const tags = new Set(post?.tags || []);
  const scored = others
    .map((candidate) => ({ candidate, shared: candidate.tags.filter((tag) => tags.has(tag)).length }))
    .sort((a, b) => (b.shared === a.shared ? b.candidate.datePublished.localeCompare(a.candidate.datePublished) : b.shared - a.shared));
  return scored.slice(0, limit).map((entry) => entry.candidate);
}

/**
 * Sitemap/llms.txt entries for the whole blog surface: the index, every
 * indexable post, and every indexable tag page. Nothing noindex enters this
 * list, so the "no noindex page in the sitemap" rule holds by construction.
 *
 * @param {unknown} blogContent
 * @returns {Array<{path: string, lastmod: string, type: string}>}
 */
export function deriveIndexableBlogEntries(blogContent) {
  const posts = derivePosts(blogContent);
  if (!blogIndexIndexable(posts)) return [];
  const tags = deriveTags(posts).filter((tag) => tag.indexable);
  return [
    { path: BLOG_INDEX_PATH, lastmod: blogLastmod(posts), type: "blog-index" },
    ...posts.filter(postIndexable).map((post) => ({ path: post.path, lastmod: post.dateModified, type: "blog-post" })),
    ...tags.map((tag) => ({ path: tag.path, lastmod: tag.lastmod, type: "blog-tag" }))
  ];
}
